// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourManagement.Api.Data;

#nullable disable

namespace TourManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourManagement.Api.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.ContractRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExistingContractId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedTerms")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExistingContractId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("ContractRequests", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.ExecutionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb");

                    b.Property<string>("FinalOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.Property<int>("TripProposalId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TripProposalId");

                    b.ToTable("ExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("StarRating")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.HotelBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CheckoutId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("HoldExpiresAt");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.HasIndex("TripId");

                    b.ToTable("HotelBookings", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.ItineraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TripId");

                    b.ToTable("ItineraryItems", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RemovalNote")
                        .HasColumnType("text");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("Supplies", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.SupplyOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceAtOrderTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplyId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupplyId");

                    b.HasIndex("TripId");

                    b.ToTable("SupplyOrders", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupSize")
                        .HasColumnType("integer");

                    b.Property<string>("Interests")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TravelerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TravelerId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripCheckout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HotelBookingId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HotelPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProposalId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TravelerId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VehicleBookingId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VehiclePriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoldExpiresAt");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TravelerId");

                    b.HasIndex("TripId");

                    b.ToTable("TripCheckouts", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDecision")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AdminDecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("CheckoutId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProposalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TravelerDecision")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TravelerDecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("RequestId");

                    b.HasIndex("Status");

                    b.HasIndex("TripId", "Version")
                        .IsUnique();

                    b.ToTable("TripProposals", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.VehicleBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckoutId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PickupLatitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("PickupLongitude")
                        .HasColumnType("decimal(11,7)");

                    b.Property<string>("PickupNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutId")
                        .IsUnique();

                    b.HasIndex("HoldExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("TripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleBookings", (string)null);
                });

            modelBuilder.Entity("TourManagement.Api.Models.Contract", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Supplier")
                        .WithMany("Contracts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TourManagement.Api.Models.ContractRequest", b =>
                {
                    b.HasOne("TourManagement.Api.Models.Contract", "ExistingContract")
                        .WithMany("ContractRequests")
                        .HasForeignKey("ExistingContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TourManagement.Api.Models.User", "Supplier")
                        .WithMany("ContractRequests")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExistingContract");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TourManagement.Api.Models.ExecutionSummary", b =>
                {
                    b.HasOne("TourManagement.Api.Models.TripProposal", "TripProposal")
                        .WithMany("ExecutionSummaries")
                        .HasForeignKey("TripProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripProposal");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Hotel", b =>
                {
                    b.HasOne("TourManagement.Api.Models.Destination", "Destination")
                        .WithMany("Hotels")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.User", "Owner")
                        .WithMany("Hotels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TourManagement.Api.Models.HotelBooking", b =>
                {
                    b.HasOne("TourManagement.Api.Models.TripCheckout", "Checkout")
                        .WithMany("HotelBookings")
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TourManagement.Api.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany("HotelBookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Room");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TourManagement.Api.Models.ItineraryItem", b =>
                {
                    b.HasOne("TourManagement.Api.Models.Destination", "Destination")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Room", b =>
                {
                    b.HasOne("TourManagement.Api.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Supply", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TourManagement.Api.Models.SupplyOrder", b =>
                {
                    b.HasOne("TourManagement.Api.Models.Supply", "Supply")
                        .WithMany("SupplyOrders")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany("SupplyOrders")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supply");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Trip", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Traveler")
                        .WithMany("Trips")
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripCheckout", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Traveler")
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany("TripCheckouts")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Traveler");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripProposal", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TourManagement.Api.Models.TripCheckout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Checkout");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Vehicle", b =>
                {
                    b.HasOne("TourManagement.Api.Models.User", "Provider")
                        .WithMany("Vehicles")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TourManagement.Api.Models.VehicleBooking", b =>
                {
                    b.HasOne("TourManagement.Api.Models.TripCheckout", "Checkout")
                        .WithOne("VehicleBooking")
                        .HasForeignKey("TourManagement.Api.Models.VehicleBooking", "CheckoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TourManagement.Api.Models.Trip", "Trip")
                        .WithMany("VehicleBookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourManagement.Api.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleBookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Contract", b =>
                {
                    b.Navigation("ContractRequests");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Destination", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Supply", b =>
                {
                    b.Navigation("SupplyOrders");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Trip", b =>
                {
                    b.Navigation("HotelBookings");

                    b.Navigation("ItineraryItems");

                    b.Navigation("SupplyOrders");

                    b.Navigation("TripCheckouts");

                    b.Navigation("VehicleBookings");
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripCheckout", b =>
                {
                    b.Navigation("HotelBookings");

                    b.Navigation("VehicleBooking");
                });

            modelBuilder.Entity("TourManagement.Api.Models.TripProposal", b =>
                {
                    b.Navigation("ExecutionSummaries");
                });

            modelBuilder.Entity("TourManagement.Api.Models.User", b =>
                {
                    b.Navigation("ContractRequests");

                    b.Navigation("Contracts");

                    b.Navigation("Hotels");

                    b.Navigation("Supplies");

                    b.Navigation("Trips");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TourManagement.Api.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
